# Generated by Django 2.1.1 on 2018-10-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('last_name', models.CharField(max_length=20)),
                ('id_document', models.IntegerField(default=0)),
                ('telephone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mandadero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=10)),
                ('telephone', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('used_to', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mandado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=200)),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandados_app.Mandadero')),
                ('done_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandados_app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('applicable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandados_app.Mandado')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='mandado_inplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandados_app.Mandado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='visited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandados_app.Mandadero'),
        ),
    ]
