# Generated by Django 2.1.1 on 2018-11-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandadero_app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mandado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=200)),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandadero_app.Mandadero')),
                ('done_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('applicable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandados_app.Mandado')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='mandado_inplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandados_app.Mandado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='visited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandadero_app.Mandadero'),
        ),
    ]
