# Generated by Django 2.1.1 on 2018-10-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandados_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandadero',
            name='password',
            field=models.CharField(default='uvg', max_length=20),
        ),
        migrations.AddField(
            model_name='mandadero',
            name='username',
            field=models.CharField(default='testman', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='uvg', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='testcli', max_length=20),
        ),
    ]
