# Generated by Django 2.1.1 on 2018-10-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandados_app', '0002_auto_20181023_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
