# Generated by Django 2.1.1 on 2018-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('last_name', models.CharField(max_length=20)),
                ('id_document', models.IntegerField(default=0)),
                ('telephone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
